FROM python:3.9

ENV DISPLAY :0

ENV USERNAME developer

WORKDIR /workspace

RUN apt update \
    && apt install -y curl

RUN curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash

RUN ln -s ~/bin/pants /bin/pants

RUN pip install poetry

# create and switch to a user
RUN echo "backus ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN useradd --no-log-init --home-dir /home/$USERNAME --create-home --shell /bin/bash $USERNAME
RUN adduser $USERNAME sudo
USER $USERNAME

WORKDIR /home/$USERNAME

RUN poetry new code

WORKDIR /home/$USERNAME/code

COPY bin .

RUN ./requiements.sh

CMD [""]